### ISSUE TITLE
是否能提供论文（Measuring Massive Multitask Chinese Understanding）中使用的测试数据集？

### ISSUE THREAD

**Issue by hijackjave** [Felixgithub2017/MMCU#1]
您好，

仓库中似乎未包含使用的测试数据集，是否能提供论文（Measuring Massive Multitask Chinese Understanding）中使用的测试数据集？

> In total, we collected **11,900 questions**, which we 
> divided into a few-shot development set and a test 
> set. The few-shot development set contains 5 
> questions per topic, amounting to 55 questions in 
> total. The test set comprises 11,845 questions.

**Comment by hijackjave** [comment]
不好意思未看清楚。

> Please send us an email to apply for free dataset download: [order@besteasy.com](mailto:order@besteasy.com) You may need to clarify your identity (Professor, College Students, NLP researcher/engineer, etc.)

**Comment by hijackjave** [comment]
不好意思未看清楚。


> Please send us an email to apply for free dataset download: [order@besteasy.com](mailto:order@besteasy.com) You may need to clarify your identity (Professor, College Students, NLP researcher/engineer, etc.)

**Comment by Felixgithub2017** [comment]
感谢关注，有什么问题欢迎反馈，一起改进
